INSERT INTO
  CONTRACT(PERSON_ID, NUMBER)
SELECT
  ID
  , CONCAT('100', LPAD(ID, 7, '0'))
FROM
  PERSON;
INSERT INTO
  CONTRACT(PERSON_ID, NUMBER)
SELECT
  ID
  , CONCAT('200', LPAD(ID, 7, '0'))
FROM
  PERSON;
INSERT INTO
  CONTRACT(PERSON_ID, NUMBER)
SELECT
  ID
  , CONCAT('300', LPAD(ID, 7, '0'))
FROM
  PERSON;
