INSERT INTO
  PERSON(FIRST_NAME, LAST_NAME)
SELECT
  CONCAT('First ', UNITS.X + TENS.X + HUNDREDS.X + THOUSANDS.X + TENTHOUSANDS.X + 1)
  , CONCAT('Last ', UNITS.X + TENS.X + HUNDREDS.X + THOUSANDS.X + TENTHOUSANDS.X + 1)
FROM
  (SELECT 0 AS X FROM DUAL
    UNION
    SELECT 1 FROM DUAL
    UNION
    SELECT 2 FROM DUAL
    UNION
    SELECT 3 FROM DUAL
    UNION
    SELECT 4 FROM DUAL
    UNION
    SELECT 5 FROM DUAL
    UNION
    SELECT 6 FROM DUAL
    UNION
    SELECT 7 FROM DUAL
    UNION
    SELECT 8 FROM DUAL
    UNION
    SELECT 9 FROM DUAL
  ) AS UNITS
  , (SELECT 0 AS X FROM DUAL
    UNION
    SELECT 10 FROM DUAL
    UNION
    SELECT 20 FROM DUAL
    UNION
    SELECT 30 FROM DUAL
    UNION
    SELECT 40 FROM DUAL
    UNION
    SELECT 50 FROM DUAL
    UNION
    SELECT 60 FROM DUAL
    UNION
    SELECT 70 FROM DUAL
    UNION
    SELECT 80 FROM DUAL
    UNION
    SELECT 90 FROM DUAL
  ) AS TENS
  , (SELECT 0 AS X FROM DUAL
    UNION
    SELECT 100 FROM DUAL
    UNION
    SELECT 200 FROM DUAL
    UNION
    SELECT 300 FROM DUAL
    UNION
    SELECT 400 FROM DUAL
    UNION
    SELECT 500 FROM DUAL
    UNION
    SELECT 600 FROM DUAL
    UNION
    SELECT 700 FROM DUAL
    UNION
    SELECT 800 FROM DUAL
    UNION
    SELECT 900 FROM DUAL
  ) AS HUNDREDS
  , (SELECT 0 AS X FROM DUAL
    UNION
    SELECT 1000 FROM DUAL
    UNION
    SELECT 2000 FROM DUAL
    UNION
    SELECT 3000 FROM DUAL
    UNION
    SELECT 4000 FROM DUAL
    UNION
    SELECT 5000 FROM DUAL
    UNION
    SELECT 6000 FROM DUAL
    UNION
    SELECT 7000 FROM DUAL
    UNION
    SELECT 8000 FROM DUAL
    UNION
    SELECT 9000 FROM DUAL
  ) AS THOUSANDS
, (SELECT 0 AS X FROM DUAL
    UNION
    SELECT 10000 FROM DUAL
    UNION
    SELECT 20000 FROM DUAL
    UNION
    SELECT 30000 FROM DUAL
    UNION
    SELECT 40000 FROM DUAL
    UNION
    SELECT 50000 FROM DUAL
    UNION
    SELECT 60000 FROM DUAL
    UNION
    SELECT 70000 FROM DUAL
    UNION
    SELECT 80000 FROM DUAL
    UNION
    SELECT 90000 FROM DUAL
  ) AS TENTHOUSANDS;
